- name: System Package Management (APT)
  hosts: all
  become: true
  tasks:
    # --- Brave Browser Installation ---
    - name: Update apt with prerequisites for Brave setup
      apt:
        name:
          - curl
          - gnupg
        state: present
      changed_when: true

    - name: Download Brave signing key
      shell: "curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg"
      args:
        creates: /usr/share/keyrings/brave-browser-archive-keyring.gpg

    - name: Add Brave repository source list
      shell: 'echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main" | tee /etc/apt/sources.list.d/brave-browser-release.list'

    - name: Update apt cache after adding Brave repository
      apt:

    # --- Core System Updates ---
    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes

    - name: Upgrade all packages to the latest version
      apt:
        name: "*"
        state: latest

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes

    - name: Install favourite tools
      apt:
        pkg:
          - alacritty
          - brave-browser
          - btop
          - curl
          - flatpak
          - git
          - iftop
          - iperf3
          - libfuse2
          - micro
          - mtr-tiny
          - ncdu
          - neofetch
          - net-tools
          - netdiscover
          - tmux
          - unzip
        state: present
