---
- hosts: ubuntu
  become: true
  vars:
    username: builder
  tasks:
    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes

    - name: Upgrade all packages to the latest version
      apt:
        name: "*"
        state: latest

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes

    - name: Install favourite tools
      apt:
        pkg:
          - btop
          - iperf3
          - iftop
          - mtr-tiny
          - tilix
          - micro
          - ncdu
          - netdiscover
          - git
          - neofetch
          - net-tools
          - unzip
          - curl
          - flatpak
        state: present
        update_cache: yes

    - name: Download starship installation script
      become: false
      get_url:
        url: https://starship.rs/install.sh
        dest: "/home/{{ username }}/install.sh"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0744

    - name: Run starship installation script
      shell: "/home/{{ username }}/install.sh -y"
      args:
        creates: /usr/local/bin/starship

    - name: Create starship config file
      become: false
      file:
        path: "/home/{{ username }}/.config/starship.toml"
        state: touch
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0664

    - name: Copy config from template - starship
      become: false
      template:
        src: templates/starship.toml
        dest: "/home/{{ username }}/.config/starship.toml"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0664

    - name: Start starship automatically in your terminal
      become: false
      lineinfile:
        path: "/home/{{ username }}/.bashrc"
        insertafter: EOF
        line: 'eval "$(starship init bash)"'

    - name: Create yaml.nanorc
      file:
        path: "/usr/share/nano/yaml.nanorc"
        state: touch

    - name: Copy config from template - nano
      template:
        src: templates/yaml.nanorc.j2
        dest: "/usr/share/nano/yaml.nanorc"
        owner: root
        group: root
        mode: 0644

    - name: Git branch name in bash
      become: false
      blockinfile:
        dest: "/home/{{ username }}/.bashrc"
        block: |
          # Show current git branch in command line
          parse_git_branch() {
          git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
          }
          export PS1="\[\033[32m\]\w\[\033[33m\]\$(parse_git_branch)\[\033[00m\] $ "
        backup: yes

    - name: Make sure fonts directory exists.
      become: false
      file:
        path: "/home/{{ username }}/.local/share/fonts"
        state: directory

    - name: Download and install InconsolataGo font
      become: false
      unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/InconsolataGo.zip
        dest: "/home/{{ username }}/.local/share/fonts"
        group: "{{ username }}"
        owner: "{{ username }}"
        mode: 0644
        remote_src: yes

    - name: flathub flatpak repo
      flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: system

    - name: Install Brave browser
      flatpak:
        name: com.brave.Browser
        state: present

    - name: Install Zed editor
      become: false
      shell: "curl -f https://zed.dev/install.sh | sh"
      args:
        creates: "/home/{{ username }}/.local/bin/zed"
